version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: fetch-ponyfill
    versions:
    - 7.0.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.5
- package-ecosystem: npm
  directory: "/badge-maker"
  schedule:
    interval: weekly
    time: "18:00"
  open-pull-requests-limit: 10
